### ISSUE TITLE
Wrong configKey for EmployeeClient

### ISSUE THREAD

**Issue by dmartinol** [piomin/sample-quarkus-microservices#101]
Link to [code](https://github.com/piomin/sample-quarkus-microservices/blob/d35039e15ac08c214603e7203164e3689ff7ffd8/organization-service/src/main/java/pl/piomin/services/organization/client/EmployeeClient.java#L17)

`configKey` should be `employee` instead of `department`

**Comment by piomin** [comment]
Fixed. Thanks
